apiVersion: v1
kind: Service
metadata:
  name: prom1
  labels:
    app: prometheus
spec:
  ports:
    - nodePort: 30001
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
    tier: Db
  type: NodePort 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-disk
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: prom-dep
  labels:
    app: prometheus
    tier: Db
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: Db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: Db
    spec:
      containers:
      - image: niraj1102/promdb:v1
        name: prom1
        imagePullPolicy: Always
        ports:
         - containerPort: 9090
           name: prom1
        volumeMounts:
         - name: prom-disk-pvc
           mountPath: /prom_disk_1
      volumes:
       - name: prom-disk-pvc
         persistentVolumeClaim:
           claimName: prom-disk
